## K-Nearest Neighbor ##
### scikit-learn ###

In [67]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets,neighbors

In [68]:
#分割训练集和测试集
np.random.seed(0)
iris=datasets.load_iris()
iris_x=iris.data
iris_y=iris.target
indices = np.random.permutation(len(iris_x))
iris_x_train = iris_x[indices[:-50]]
iris_y_train = iris_y[indices[:-50]] 
iris_x_test  = iris_x[indices[-50:]]
iris_y_test  = iris_y[indices[-50:]]

In [69]:
knn = neighbors.KNeighborsClassifier() 
knn.fit(iris_x_train, iris_y_train)  
iris_y_predict = knn.predict(iris_x_test) 
probility=knn.predict_proba(iris_x_test)
iris_y_predict,iris_y_test

(array([0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2,
        0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 1, 2, 1, 0,
        0, 0, 2, 1, 2, 0]),
 array([0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2,
        0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0,
        0, 0, 2, 1, 2, 0]))

In [70]:
print('Accuracy:' ,(iris_y_predict == iris_y_test).sum()*100/iris_y_predict.shape[0],'%')

Accuracy: 96.0 %


### numpy ###

In [23]:
class KNN(object):
     
    """
    K-Nearest Neighbor
    参数
    ------
    data: 训练集数据
    target: 训练集种类
    priddata: 测试集数据
    pridtarget: 测试集类别
    distance: 距离
    K: K值，取最近K个点
    返回值
    -------
    pridtarget: 测试集类别
    """
    
    def __init__(self,data,target,priddata,K=5):
        self._data = data
        self._target = target
        self._priddata = priddata
        self._distance = np.zeros(self._data.shape[0])
        self.pridtarget = np.zeros(self._priddata.shape[0])
        self._K = K
    
    """
    计算距离（欧氏距离）
    """
    def _cal_dist(self,x,y):
        return np.sum((x - y) ** 2) ** 0.5
    
    """
    投票找出出现次数最多的类别
    参数
    ------
    vote: 邻近K个数据的类别
    返回值
    -------
    max_vote: 出现次数最多的类别    
    """
    def _cnt_vote(self,vote):
        vote_class = {}
        for i in vote:
            if i in vote_class:
                vote_class[i]+=1
            else:
                vote_class[i]=1
        max_vote = sorted(vote_class.items(),reverse=True)[0][0]
        return max_vote
    
    def pridect(self):
        for j in range(self._priddata.shape[0]):
            for i in range(self._data.shape[0]):
                self._distance[i] = self._cal_dist(self._data[i],self._priddata[j])#计算距离
            vote = self._target[self._distance.argsort()[:self._K]]                #最短K个值进行投票
            self.pridtarget[j] = self._cnt_vote(vote)
        return self.pridtarget

In [24]:
knn =KNN(iris_x_train,iris_y_train,iris_x_test,3)
knn_pridect = knn.pridect()
knn_pridect,iris_y_test

(array([0., 0., 1., 2., 2., 0., 0., 0., 1., 1., 0., 0., 1., 0., 2., 1., 2.,
        1., 0., 2., 0., 2., 0., 0., 2., 0., 2., 1., 1., 1., 2., 2., 2., 2.,
        0., 1., 2., 2., 0., 1., 1., 2., 1., 0., 0., 0., 2., 1., 2., 0.]),
 array([0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2,
        0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0,
        0, 0, 2, 1, 2, 0]))

In [25]:
print('Accuracy:' ,(knn_pridect == iris_y_test).sum()*100/iris_y_predict.shape[0],'%')

Accuracy: 94.0 %


## K-Dimension Tree ##

In [53]:
iris_x_train = iris_x[indices[:-50]]
iris_x_train
a = iris_x_train[:,0].argsort(axis = 0)

In [54]:
sortdata = iris_x_train[a]

In [56]:
sortdata[round(sortdata.shape[0]/2)]

array([5.8, 2.6, 4. , 1.2])

In [62]:
class QuickSort(object):
    "Quick Sort to get medium number"

    def __init__(self, low, high, array):
        self._array = array
        self._low = low
        self._high = high
        self._medium = (low+high+1)//2 # python3中的整除

    def get_medium_num(self):
        return self.quick_sort_for_medium(self._low, self._high, 
                                          self._medium, self._array)

    def quick_sort_for_medium(self, low, high, medium, array): #用快速排序来获取中位数
        if high == low:
            return array[low] # find medium
        if high > low:
            index, partition = self.sort_partition(low, high, array); 
            #print array[low:index], partition, array[index+1:high+1]
            if index == medium:
                return partition
            if index > medium:
                return self.quick_sort_for_medium(low, index-1, medium, array)
            else:
                return self.quick_sort_for_medium(index+1, high, medium, array)

    def quick_sort(self, low, high, array):  #正常的快排
        if high > low:
            index, partition = self.sort_partition(low, high, array); 
            #print array[low:index], partition, array[index+1:high+1]
            self.quick_sort(low, index-1, array)
            self.quick_sort(index+1, high, array)

    def sort_partition(self, low, high, array): # 用第一个数将数组里面的数分成两部分
        index_i = low
        index_j = high
        partition = array[low]
        while index_i < index_j:
            while (index_i < index_j) and (array[index_j] >= partition):
                index_j -= 1
            if index_i < index_j:
                array[index_i] = array[index_j]
                index_i += 1
            while (index_i < index_j) and (array[index_i] < partition):
                index_i += 1
            if index_i < index_j:
                array[index_j] = array[index_i]
                index_j -= 1
        array[index_i] = partition
        return index_i, partition
    
class KDTree(object):

    def __init__(self, input_x):
        self._input_x = np.array(input_x)
        (data_num, axes_num) = np.shape(self._input_x)
        self._data_num = data_num
        self._axes_num = axes_num
        self._nearest = None  #用来存储最近的节点
        return

    def construct_kd_tree(self):
        return self._construct_kd_tree(0, 0, self._input_x)

    def _construct_kd_tree(self, depth, axes, data):
        if not data.any():
            return None
        axes_data = data[:, axes].copy()
        qs = QuickSort(0, axes_data.shape[0]-1, axes_data)
        medium = qs.get_medium_num() #找到轴的中位数

        data_list = []
        left_data = []
        right_data = []
        data_range = range(np.shape(data)[0])
        for i in data_range:   # 跟中位数相比较
            if data[i][axes] == medium:  #相等
                data_list.append(data[i])
            elif data[i][axes] < medium: 
                left_data.append(data[i])
            else:
                right_data.append(data[i])

        left_data = np.array(left_data)
        right_data = np.array(right_data)
        left = self._construct_kd_tree(depth+1, (axes+1)% self._axes_num, left_data)
        right = self._construct_kd_tree(depth+1, (axes+1)% self._axes_num, right_data)
        #[树的深度，轴，中位数，该节点的数据，左子树，右子树]
        root = [depth, axes, medium, data_list, left, right] 
        return root

    def print_kd_tree(self, root): #打印kd树
        if root:
            [depth, axes, medium, data_list, left, right] = root
            print('{} {}'.format('    '*depth, data_list[0]))
            if root[4]:
                self.print_kd_tree(root[4])
            if root[5]:
                self.print_kd_tree(root[5])

In [65]:
input_x = iris_x[indices[:-50]]
kd = KDTree(input_x)
tree = kd.construct_kd_tree()

In [66]:
tree

[0,
 0,
 5.8,
 [array([5.8, 2.8, 5.1, 2.4]),
  array([5.8, 2.6, 4. , 1.2]),
  array([5.8, 2.7, 5.1, 1.9])],
 [1,
  1,
  3.1,
  [array([4.8, 3.1, 1.6, 0.2]), array([4.6, 3.1, 1.5, 0.2])],
  [2,
   2,
   3.9,
   [array([5.2, 2.7, 3.9, 1.4]), array([5.6, 2.5, 3.9, 1.1])],
   [3,
    3,
    0.3,
    [array([4.8, 3. , 1.4, 0.3]), array([4.5, 2.3, 1.3, 0.3])],
    [4,
     0,
     4.8,
     [array([4.8, 3. , 1.4, 0.1])],
     [5,
      1,
      3.0,
      [array([4.3, 3. , 1.1, 0.1])],
      [6, 2, 1.4, [array([4.4, 2.9, 1.4, 0.2])], None, None],
      None],
     [5, 1, 3.0, [array([4.9, 3. , 1.4, 0.2])], None, None]],
    [4,
     0,
     5.1,
     [array([5.1, 2.5, 3. , 1.1])],
     [5,
      1,
      2.3,
      [array([5. , 2.3, 3.3, 1. ])],
      [6, 2, 3.5, [array([5. , 2. , 3.5, 1. ])], None, None],
      None],
     [5,
      1,
      2.9,
      [array([5.6, 2.9, 3.6, 1.3])],
      [6, 2, 3.8, [array([5.5, 2.4, 3.8, 1.1])], None, None],
      None]]],
   [3,
    3,
    1.5,
    [arra