In [1]:
import time
import matplotlib.pyplot as plt
import numpy as np
from scipy import linalg
from sklearn import datasets

In [2]:
def Fig1_svd(A, k, p):
    """
    A = QQ'A = QB = QUhatDV' = UDV'
    parameters:
        A - m*n matrix
        k - target rank
        p - over-sampling parameter
    Outputs:
        matrices U,D,V in an approximate rank-(k+p) svd of A
    """
    m, n = A.shape
    # form an n*(k + p) Gaussian random matrix G
    G = np.random.rand(n, k+p)
    # form the sample matrix Y = AG.
    Y = A@G
    # orthonormalize the columns of the sample matrix Q = orth(Y)
    Q = linalg.orth(Y)
    # form the (k + p) * n matrix B = Q'*A
    B = Q.T@A
    # form the svd of the small matrix B
    Uhat, D, Vt = np.linalg.svd(B, full_matrices=False)
    V = Vt.T
    # drop the last p components
    Uhat = Uhat[:,:k]; D = D[:k]; V = V[:,:k];
    # form U = Q * Uhat
    U = Q@Uhat
    return U, D, V, Q

In [3]:
irisset = datasets.load_iris()
irisset = np.array(irisset.data)

In [10]:
Fig1_svd(irisset.T,2,0)

(array([[ 0.75041975, -0.30035081],
        [ 0.38252725, -0.49580676],
        [ 0.51046409,  0.64359951],
        [ 0.17311708,  0.49974465]]),
 array([95.95799622, 17.48853645]),
 array([[ 0.06164426, -0.12957771],
        [ 0.05808699, -0.11196769],
        [ 0.05678825, -0.11788306],
        [ 0.05667151, -0.10597036],
        [ 0.06126087, -0.13069534],
        [ 0.06754162, -0.12931464],
        [ 0.05751588, -0.11529804],
        [ 0.06099555, -0.12134514],
        [ 0.05377821, -0.10054557],
        [ 0.05883719, -0.11398016],
        [ 0.06531959, -0.13671991],
        [ 0.05996346, -0.11423018],
        [ 0.05712456, -0.11310783],
        [ 0.05161851, -0.11556112],
        [ 0.06804773, -0.16313506],
        [ 0.07081698, -0.15600232],
        [ 0.06541376, -0.14403512],
        [ 0.06182466, -0.12672016],
        [ 0.06930866, -0.1344894 ],
        [ 0.06355255, -0.13154515],
        [ 0.0651876 , -0.12085455],
        [ 0.06333432, -0.12585256],
        [ 0.05600488, -0.1